### ISSUE TITLE
Getting affiliation type from the API

### ISSUE THREAD

**Issue by zchandler** [SU-SWS/stanford_capx#138] opened 2017-06-05 00:07 UTC
Hi Team,
No urgency on this one, I was just thinking about how to filter people profiles by affiliation type more cleanly than we do right now.  I see that in the API, `acadmicOffices.affiliation.Type` includes the information we are looking for, just not in a format that is readily usable. The value will be "University - Faculty" which is a StanfordWho type of distinction (because some faculty are Hospital, not University), which sounds weird if we pull that text string in as-is on a website.  So here is my question: can we make a Select List field in Drupal that uses these strings: "University - Faculty" and "University - Staff" as keys, and we use the more natural sounding "Faculty" and "Staff" as the values of the key-value pairs? And if we do that can we import straight from the API to populate this field, and then translate it to the preferred language? Do you see where I am going with this? Just wondering.
Thanks Guys.
Z.

**Comment by wkcwells** [comment] 2017-06-07 01:59
Hi Zach, 
(You might have guessed that I would weigh in here :)   As you may recall, we implemented a manual workaround to address a related issue on the SITP site:

<img width="156" alt="localaffiliation" src="https://user-images.githubusercontent.com/10645450/26859004-a1727bee-4ae9-11e7-809a-7b3705c8b78c.png">
because profiles were ending up in the wrong category based on the affiliation field.  

I would **really** like to get rid of this workaround.  I believe that the root problem is that the affiliation field was intended to be used to connect a profile to a template, not as a primary designator of the role that the profile owner plays at the university.  But (at least at the time), there was no other field that could be used for this.

Can we roll these two issues together?  I believe that they can be solved by the same mechanism, but verifying that will no doubt take more detailed requirements analysis, which I am happy to help with.
Thanks.

**Comment by sherakama** [comment] 2017-06-08 16:07
@zchandler,

Full disclosure, I haven't tested this thought yet, but you may want to use the new capx_tamper functionality to change the language before it is saved to Drupal. See the user guide for more information on how to do that: https://sites-jumpstart.stanford.edu/jumpstart-user-guide/stanford-content/people/tampering-imported-profile-data-capx

This would allow you to change the data before it is saved to Drupal making it much easier to work with. Also, say you wanted to combine Affiliated Faculty and Faculty in to one, you could tamper both of those terms in to one common language, effectively grouping them together on the Drupal end.

Let me know if you have success with this.

**Comment by sherakama** [comment] 2017-06-08 16:12
@wkcwells Are you looking for a change to the affiliation field or some other type of role designation for people?  `$.shortTitle.affiliation` has a role assigned to the title which I believe is based on the context of the title. This is the same with `$.titles.*.affiliation`. 

If none of those affiliation terms have the data you are looking for we will have to get in touch with Tina about where that data is available and how to present it.

**Comment by zchandler** [comment] 2017-07-31 21:27
@sherakama Wow! Thanks for including the tamper plugins, that is pretty *expletive* awesome!  I will no doubt use this. Did @ksharp-drupal have anything to do with this? Sounds like him. :)

**Comment by sherakama** [comment] 2017-07-31 21:43
A lot of the original idea and planning was done some time ago with @ksharp-drupal but the version you are using is the great work of @pookmish.

**Comment by zchandler** [comment] 2017-07-31 22:13
Thanks @pookmish !!

**Comment by pookmish** [comment] 2017-07-31 22:17
You got it 👍

**Closed as completed** 2018-03-28 05:33 UTC
